services:
  - type: web
    name: buildiofy-website
    env: node
    region: oregon
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false